import {
    Form,
    useNavigate,
    useNavigation,
    useActionData,
    json,
    redirect,
} from "react-router-dom";

import classes from "./EventForm.module.css";

function EventForm({ method, event }) {
    const data = useActionData(); // we can access to data, returned by action
    const navigate = useNavigate();
    const navigation = useNavigation(); // we can access to navigation object(can get information about current active transition & whether the action is completed)

    const isSubmitting = navigation.state === "submitting";

    function cancelHandler() {
        navigate("..");
    }

    return (
        // Form makes it available to pass the whole data to action
        <Form method={method} className={classes.form}>
            {data && data.errors && (
                <ul>
                    {Object.values(data).map((err) => (
                        <li key={err}>{err}</li>
                    ))}
                </ul>
            )}
            <p>
                <label htmlFor="title">Title</label>
                <input
                    id="title"
                    type="text"
                    name="title"
                    required
                    defaultValue={event ? event.title : ""}
                />
            </p>
            <p>
                <label htmlFor="image">Image</label>
                <input
                    id="image"
                    type="url"
                    name="image"
                    defaultValue={event ? event.image : ""}
                />
            </p>
            <p>
                <label htmlFor="date">Date</label>
                <input
                    id="date"
                    type="date"
                    name="date"
                    required
                    defaultValue={event ? event.date : ""}
                />
            </p>
            <p>
                <label htmlFor="description">Description</label>
                <textarea
                    id="description"
                    name="description"
                    rows="5"
                    required
                    defaultValue={event ? event.description : ""}
                />
            </p>
            <div className={classes.actions}>
                <button
                    type="button"
                    onClick={cancelHandler}
                    disabled={isSubmitting}
                >
                    Cancel
                </button>
                <button disabled={isSubmitting}>
                    {isSubmitting ? "Submitting..." : "Save"}
                </button>
            </div>
        </Form>
    );
}

export async function action({ request, params }) {
    // we need to get the captured form data
    const method = request.method; // the request method automatically generated by react router
    const data = await request.formData(); // this includes form data

    const eventData = {
        title: data.get("title"),
        image: data.get("image"),
        date: data.get("date"),
        description: data.get("description"),
    };

    let newUrl = "http://localhost:8080/events";
    let editUrl = "http://localhost:8080/events/" + params.eventId;

    const response = await fetch(method === "PATCH" ? editUrl : newUrl, {
        method: method,
        headers: {
            "Content-Type": "application/json",
        },
        body: JSON.stringify(eventData),
    });

    if (response.status === 422) return response;

    if (!response.ok)
        throw json({ message: "Could not save event." }, { status: 500 });

    return redirect("/events");
}
export default EventForm;
